rename:
    noitem: "Du musst ein Gegenstand in der Hand halten!"
    renamed: "Du hast §a{0} §7umbenannt zu §a{1}§7."
lore:
    add: "Du hast §a{0} §7die Lore §a{1}§7 hinzugefügt!"
    noitem: "Du musst ein Gegenstand in der Hand halten!"
    remove: "Du hast {0} die Loren entfernt!"
warp:
    notfound: "Warp §c{0} §7wurde nicht gefunden!"
    teleport: "Du wurdest zum Warp §a{0} §7teleportiert."
    delete: "Warp §c{0} §7wurde gelöscht."
    set: "Warp §a{0} §7wurde mit dem Anzeigename §a{1} §7hinzugefügt."
    allyexist: "Der Warp §c{0} §7exestiert bereits!"
    reset: "Du hast den Warp §a{0} §7umgesetzt."
    list: "Hier ist eine Liste aller Warps:\n§a{0}"
home:
    notfound: "Zuhause §c{0} §7wurde nicht gefunden!"
    teleport: "Du wurdest zum Home §a{0} §7teleportiert."
    delete: "Zuhause §c{0} §7wurde gelöscht."
    set: "Zuhause §a{0} §7wurde hinzugefügt."
    allyexist: "Das Zuhause §c{0} §7exestiert bereits!"
    list: "Hier ist eine Liste deiner Homes:\n§a{0}"
speed:
    walk: "Deine Laufgeschwindigkeit wurde auf §a{0}§7 gesetzt."
    fly: "Deine Fluggeschwindigkeit wurde auf §a{0}§7 gesetzt."
fly:
    "on": "Dein Flugmodus wurde §aeingeschalten."
    "off": "Dein Flugmudus wurde §causgeschalten."
    other:
        "on": "Der Flugmodus von §a{0}§7 wurde §aeingeschalten."
        "off": "Der Flugmodus von §a{0}§7 wurde §causgeschalten."
gamemode:
    survival: "Deim Spielmodus wurde auf §2Überleben §7gesetzt."
    creative: "Deim Spielmodus wurde auf §cKreativ §7gesetzt."
    adventure: "Deim Spielmodus wurde auf §6Abenteuer §7gesetzt."
    spectator: "Deim Spielmodus wurde auf §eZuschauer §7gesetzt."
    unknown: "§cDieser Spielmodus ist unbekannt!"
    other:
        survival: "Du hast den  Spielmodus von §a{0}§7 auf §2Überleben §7gesetzt."
        creative: "Du hast den  Spielmodus von §a{0}§7 auf §cKreativ §7gesetzt."
        adventure: "Du hast den  Spielmodus von §a{0}§7 auf §6Abenteuer §7gesetzt."
        spectator: "Du hast den  Spielmodus von §a{0}§7 auf §eZuschauer §7gesetzt."
acf-core:
    permission_denied: "Du hast nicht die benötigte Berechtigung um diesen Befehl auszuführen."
    error_generic_logged: "Ein Fehler ist aufgetreten. Dieses Problem wurde protokolliert. Entschuldigung für die Unannehmlichkeiten."
    unknown_command: "Unbekannter Befehl, gib <c2>/help</c2> ein, um Hilfe zu bekommen."
    invalid_syntax: "Verwendung: <c2>{command}</c2> <c3>{syntax}</c3>"
    error_prefix: "Fehler: {message}"
    error_performing_command: "Beim Ausführen des Befehls ist ein Fehler aufgetreten."
    info_message: "{message}"
    please_specify_one_of: "Fehler: Du must aus diesen Optionen wählen (<c2>{valid}</c2>)."
    must_be_a_number: "Fehler: Du musst eine Zahl eingeben."
    must_be_min_length: "Fehler: Du musst mindestens {min} Buchstaben eingeben."
    must_be_max_length: "Fehler: Du kannst maximal {max} Buchstaben eingeben."
    please_specify_at_most: "Fehler: Bitte gib eine Zahl kleiner oder gleich {max} ein."
    please_specify_at_least: "Error: Bitte gib eine Zahl größer oder gleich {min} ein."
    not_allowed_on_console: "Fehler: Die Konsole darf diesen Befehl nicht ausführen."
    could_not_find_player: "Fehler: Es konnte kein Spieler mit dem Namen <c2>{search}</c2> gefunden werden."
    help_format: "<c1>{command}</c1> <c2>{parameters}</c2> <c3>{separator} {description}</c3>"
    no_command_matched_search: "Es wurde kein mit <c2>{search}</c2> übereinstimmender Befehl gefunden."
    help_page_information: "- Seite <c2>{page}</c2> von <c2>{totalpages}</c2> (<c3>{results}</c3> Ergebnisse)."
    help_no_results: "Fehler: Keine weiteren Ergebnisse."
    help_header: "<c3>=== </c3><c1>Hilfe für </c1><c2>{commandprefix}{command}</c2><c3> ===</c3>"
    help_detailed_header: "<c3>=== </c3><c1>Detaillierte Hilfe für </c1><c2>{commandprefix}{command}</c2><c3> ===</c3>"
    help_detailed_command_format: "<c1>{command}</c1> <c2>{parameters}</c2> <c3>{separator} {description}</c3>"
    help_detailed_parameter_format: "<c2>{name}</c2>: <c3>{description}</c3>"
    help_search_header: "<c3>=== </c3><c1>Suchergebnisse für </c1><c2>{commandprefix}{command} {search}</c2><c3> ===</c3>"
acf-minecraft:
    invalid_world: "Fehler: Diese Welt gibt es nicht."
    you_must_be_holding_item: "Fehler: Du musst einen Gegenstand in deiner Haupthand halten."
    player_is_vanished_confirm: "Warnung: <c2>{vanished}</c2> ist getarnt. Lasse die Tarnung nicht auffliegen!\nUm die Aktion zu bestätigen, hänge <c2>:confirm</c2> hinten an den Namen an.\nBsp: <c2>{vanished}:confirm</c2>"
    username_too_short: "Fehler: Spielername zu kurz, er muss mindestens drei Buchstaben lang sein."
    is_not_a_valid_name: "Fehler: <c2>{name}</c2> ist kein gültiger Spielername."
    multiple_players_match: "Fehler: Es gibt mehrere Spieler deren Namen mit <c2>{search}</c2> <c3>({all})</c3> übereinstimmen, du musst genauer sein."
    no_player_found_server: "Es wurde auf diesem Server kein mit <c2>{search}</c2> übereinstimmender Spieler gefunden."
    no_player_found_offline: "Es wurde kein mit <c2>{search}</c2> übereinstimmender Spieler gefunden."
    no_player_found: "Es wurde kein mit <c2>{search}</c2> übereinstimmender Spieler gefunden."
    location_please_specify_world: "Fehler: Bitte die Welt angeben. Beispiel: <c2>world:x,y,z</c2>."
    location_please_specify_xyz: "Fehler: Bitte die Koordinaten x, y und z angeben. Beispiel: <c2> Welt: x, y, z </ c2>."
    location_console_not_relative: "Fehler: Konsole darf keine relativen Koordinaten für den Standort verwenden."